services:
  db:
    image: postgres:16
    container_name: coffee_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: coffee123
      POSTGRES_DB: coffee_pos
    ports:
      - "5432:5432"
    volumes:
      - coffee_db_data:/var/lib/postgresql/data

volumes:
  coffee_db_data:
